- name: add repo
  apt_repository:
    repo: ppa:gluster/glusterfs-4.1

- name: Installs necessary packages
  apt:
    update_cache: yes
    pkg: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - php
    - git
    - glusterfs-client

- name: Push future default virtual host configuration
  copy:
    src: files/awesome-app
    dest: /etc/apache2/sites-available/awesome-app.conf
    mode: 0640

- name: Activates our virtualhost
  command: a2ensite awesome-app

- name: Check that our config is valid
  command: apache2ctl configtest
  register: result
  ignore_errors: True

- name: Rolling back - Restoring old default virtualhost
  command: a2ensite 000-default
  when: result is failed

- name: Rolling back - Removing out virtualhost
  command: a2dissite awesome-app
  when: result is failed

- name: Rolling back - Ending playbook
  fail:
    msg: "Configuration file is not valid. Please check that before re-running the playbook."
  when: result is failed

- name: mount gluster cluster
  command: mount.glusterfs ceph1:/replicated /var/www

- name: Deploy our awesome application
  git:
    repo: https://github.com/Veles/ansible-tuto-demosite.git
    dest: /var/www/awesome-app
  tags: deploy
  run_once: true

- name: Deactivates the default virtualhost
  command: a2dissite 000-default

- name: Deactivates the default ssl virtualhost
  command: a2dissite default-ssl
  notify:
    - restart apache

- name: create consul directory
  file:
    path: /etc/consul.d
    state: directory
    mode: 0755

- name: Pushes mem check
  template:
    src: files/mem.sh
    dest: /root/mem.sh
    mode: 0640
    owner: root
    group: root

- name: Pushes web check
  template:
    src: files/web.json
    dest: /etc/consul.d/web.json
    mode: 0640
    owner: root
    group: root

- name: Pushes mem Check
  template:
    src: files/mem.json
    dest: /etc/consul.d/mem.json
    mode: 0640
    owner: root
    group: root


- name: Pushes ping check
  template:
    src: files/ping.json
    dest: /etc/consul.d/ping.json
    mode: 0640
    owner: root
    group: root

- name: restart consul
  service:
    name: consul
    state: restarted
