- hosts: linux
  roles:
     - { role: hosts }

- hosts: consul-server
  roles:
     - { role: consul-server }


- hosts: consul-client
  roles:
     - { role: consul-client }

- hosts: ceph-master
  roles:
     - { role: glusterfs-master }

- hosts: ceph
  roles:
     - { role: glusterfs-slave }

- hosts: web
  roles:
     - { role: apache }

- hosts: haproxy
  roles:
     - { role: haproxy }

- hosts: nginx
  roles:
     - { role: nginx }
