- hosts: linux
  roles:
     - { role: hosts }

- hosts: web
  roles:
     - { role: apache }
 
- hosts: nginx
  roles:
     - { role: nginx }

- hosts: haproxy
  roles:
     - { role: haproxy }

- hosts: consul-server
  roles:
     - { role: consul-server } 
 
- hosts: consul-client
  roles:
     - { role: consul-client } 
